# bossphorus Continuous Integration.
# Uses [workflows](https://circleci.com/docs/2.0/workflows/)

version: 2
jobs:
    prepare:
        docker:
            - image: circleci/python:3.7.1
        steps:
            - checkout
    bossphorus_build:
        docker:
            - image: circleci/python:3.7.1
        steps:
            - checkout
            - restore_cache:
                key: deps01-{{ .Branch }}-{{ checksum "bossphorus/poetry.lock" }}
            - run:
                name: Install dependencies
                command: |
                    python3 -m venv bvenv
                    . bvenv/bin/activate
                    pip install poetry
                    cd bossphorus
                    poetry install
            - save_cache:
                key: deps01-{{ .Branch }}-{{ checksum "bossphorus/poetry.lock" }}
                paths:
                    - "bvenv"
    bossphorus_lint:
        docker:
            - image: circleci/python:3.7.1
        steps:
            - checkout
            - restore_cache:
                key: deps01-{{ .Branch }}-{{ checksum "bossphorus/poetry.lock" }}
            - run:
                name: Lint bossphorus
                command: |
                    . bvenv/bin/activate
                    cd bossphorus
                    python -m pylint bossphorus
    bossphorus_test:
        docker:
            - image: circleci/python:3.7.1
        steps:
            - checkout
            - restore_cache:
                key: deps01-{{ .Branch }}-{{ checksum "bossphorus/poetry.lock" }}
            - run:
                name: Test bossphorus (pytest)
                command: |
                    . bvenv/bin/activate
                    python -m pytest bossphorus

workflows:
    version: 2
    test_all:
        jobs:
            - prepare
            - bossphorus_build:
                requires:
                    - prepare
            - bossphorus_lint:
                requires:
                    - bossphorus_build
            - bossphorus_test:
                requires:
                    - bossphorus_build
            - collect_artifacts:
                requires:
                    - bossphorus_test
                    - bossphorus_lint
