# bossphorus Continuous Integration.
# Uses [workflows](https://circleci.com/docs/2.0/workflows/)

version: 2
jobs:
    lint_bossphorus:
        docker:
            - image: circleci/python:3.7.1
        steps:
            - checkout
            - run: python3 -m pylint bossphorus
    build_bossphorus:
        docker:
            - image: circleci/python:3.7.1
        steps:
            - checkout
            - restore_cache:
                key: deps1-{{ .Branch }}-{{ checksum "bossphorus/requirements.txt" }}
            - run:
                name: Install dependencies
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r bossphorus/requirements.txt
            - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "bossphorus/requirements.txt" }}
                paths:
                    - "venv"
    test_bossphorus:
        docker:
            - image: circleci/python:3.7.1
        steps:
            - checkout
            - run: python3 -m pytest bossphorus
workflows:
    version: 2
    test_all:
        jobs:
            - build_bossphorus
            - lint_bossphorus:
                requires:
                    - build_bossphorus
            - test_bossphorus:
                requires:
                    - build_bossphorus
