# bossphorus Continuous Integration.
# Uses [workflows](https://circleci.com/docs/2.0/workflows/)

version: 2
jobs:
    build_bossphorus:
        docker:
            - image: circleci/python:3.7.1
        steps:
            - checkout
            - run: pip3 install --user pytest
            - run: python3 -m pytest bossphorus
workflows:
    version: 2
    test_all:
        jobs:
            - build_bossphorus
