# bossphorus Continuous Integration.
# Uses [workflows](https://circleci.com/docs/2.0/workflows/)

version: 2
jobs:
    bossphorus_build:
        docker:
            - image: circleci/python:3.7.1
        steps:
            - checkout
            - restore_cache:
                key: deps01-{{ .Branch }}-{{ checksum "bossphorus/requirements.txt" }}
            - run:
                name: Install dependencies
                command: |
                    python3 -m venv bvenv
                    . bvenv/bin/activate
                    pip install -r bossphorus/requirements.txt
            - save_cache:
                key: deps01-{{ .Branch }}-{{ checksum "bossphorus/requirements.txt" }}
                paths:
                    - "bvenv"
    bossphorus_lint:
        docker:
            - image: circleci/python:3.7.1
        steps:
            - checkout
            - restore_cache:
                key: deps01-{{ .Branch }}-{{ checksum "bossphorus/requirements.txt" }}
            - run:
                name: Lint bossphorus
                command: |
                    . bvenv/bin/activate
                    python -m pylint bossphorus
    bossphorus_test:
        docker:
            - image: circleci/python:3.7.1
        steps:
            - checkout
            - restore_cache:
                key: deps01-{{ .Branch }}-{{ checksum "bossphorus/requirements.txt" }}
            - run:
                name: Test bossphorus (pytest)
                command: |
                    . bvenv/bin/activate
                    python -m pytest bossphorus

    marmara_build:
        docker:
            - image: circleci/python:3.7.1
        steps:
            - checkout
            - restore_cache:
                key: deps01-{{ .Branch }}-{{ checksum "marmara/requirements.txt" }}
            - run:
                name: Install dependencies
                command: |
                    python3 -m venv mvenv
                    . mvenv/bin/activate
                    pip install -r marmara/requirements.txt
            - save_cache:
                key: deps01-{{ .Branch }}-{{ checksum "marmara/requirements.txt" }}
                paths:
                    - "mvenv"
    marmara_lint:
        docker:
            - image: circleci/python:3.7.1
        steps:
            - checkout
            - restore_cache:
                key: deps01-{{ .Branch }}-{{ checksum "marmara/requirements.txt" }}
            - run:
                name: Lint marmara
                command: |
                    . mvenv/bin/activate
                    python -m pylint marmara
    marmara_test:
        docker:
            - image: circleci/python:3.7.1
        steps:
            - checkout
            - restore_cache:
                key: deps01-{{ .Branch }}-{{ checksum "marmara/requirements.txt" }}
            - run:
                name: Test marmara (pytest)
                command: |
                    . mvenv/bin/activate
                    python -m pytest marmara

workflows:
    version: 2
    test_all:
        jobs:
            - bossphorus_build
            - bossphorus_lint:
                requires:
                    - bossphorus_build
            - bossphorus_test:
                requires:
                    - bossphorus_build
            - marmara_build
            - marmara_lint:
                requires:
                    - marmara_build
            - marmara_test:
                requires:
                    - marmara_build
            - collect_artifacts:
                requires:
                    - bossphorus_build
                    - bossphorus_lint
                    - marmara_build
                    - marmara_lint
